<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.16" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JobBoardPlatform.Core\JobBoardPlatform.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Dto\RequestDto\CityDto\" />
    <Folder Include="Common\Dto\RequestDto\SkillDto\" />
    <Folder Include="Common\Dto\ResponseDto\Common\" />
  </ItemGroup>

</Project>
