<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Common\Extensions\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JobBoardPlatform.Core\JobBoardPlatform.Core.csproj" />
  </ItemGroup>

</Project>
